/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VizSourceFileIdRouteImport } from './routes/viz/$sourceFileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VizSourceFileIdRoute = VizSourceFileIdRouteImport.update({
  id: '/viz/$sourceFileId',
  path: '/viz/$sourceFileId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/viz/$sourceFileId': typeof VizSourceFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/viz/$sourceFileId': typeof VizSourceFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/viz/$sourceFileId': typeof VizSourceFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/viz/$sourceFileId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/viz/$sourceFileId'
  id: '__root__' | '/' | '/viz/$sourceFileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VizSourceFileIdRoute: typeof VizSourceFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viz/$sourceFileId': {
      id: '/viz/$sourceFileId'
      path: '/viz/$sourceFileId'
      fullPath: '/viz/$sourceFileId'
      preLoaderRoute: typeof VizSourceFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VizSourceFileIdRoute: VizSourceFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
